box: oraclebase/oracle-7
vm_name: ol7_121_prm
mem_size: 4096
cpus: 4
public_ip: 192.168.1.140
disk1_name: D:\VIRTUALBOX\ol7_121_prm\ol7_121_u01.vdi
disk2_name: D:\VIRTUALBOX\ol7_121_prm\ol7_121_u02.vdi
non_rotational: 'on'
disk_size: 100
