Vagrant.configure("2") do |config|
    config.vm.box = "generic/oracle8"
    config.vm.hostname = "testvm"
    config.vm.provider :vmware_esxi do |esxi|
      esxi.esxi_hostname = "192.168.1.12"
      esxi.esxi_username = "root"
      esxi.esxi_password = "Nithin#0712"
      esxi.esxi_hostport = "22"
      esxi.esxi_virtual_network = "PRODUCTION"
      esxi.esxi_disk_store = "VMSTORE"
      esxi.guest_name = "oel8-vm"
      esxi.guest_memsize = "2048"
      esxi.guest_numvcpus = "2"
      esxi.guest_disk_type = 'thin'
      esxi.guest_guestos = 'centos-64'
    end
  end
  